name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm ci || true
      - name: Lint
        run: |
          npx eslint src/ || true
      - name: Build/Package Extension
        run: |
          zip -r bookmark-sync-drive.zip src/ assets/
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension-package
          path: bookmark-sync-drive.zip
