name: BookDrive CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*' # Run on version tags like v1.0.0
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint:check

      - name: Run tests
        run: npm test

  build-and-package:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Package extension
        id: package
        run: |
          npm run package
          echo "zip_path=$(ls bookdrive-extension-v*.zip)" >> $GITHUB_OUTPUT

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: ${{ steps.package.outputs.zip_path }}

  create-draft-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    needs: build-and-package
    if: startsWith(github.ref, 'refs/tags/') # Only run this job for new tags
    permissions:
      contents: write # Required to create a GitHub release
    steps:
      - name: Download packaged extension
        uses: actions/download-artifact@v4
        with:
          name: extension-package

      - name: Create Draft Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
          body: |
            ## New Release

            **Note:** This is a draft release. Please update the release notes with the relevant changes from your `CHANGELOG.md` or `RELEASE.md` before publishing.
          draft: true # This creates a draft release, it is NOT published automatically
          prerelease: false
