# BookDrive CI/CD Pipeline
# - Lint, format, test, build, and package
# - Release on tag push
# - Node 22+, runs on Ubuntu
# - Caches npm for speed
# - Fails fast with clear logs
# - Updated to latest action versions for security and performance
#
# For details, see CONTRIBUTING.md and BUILD.md

name: BookDrive CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '22'
  NPM_VERSION: '10'

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npm run format:check

      - name: Run ESLint
        run: npm run lint:check

      - name: Run tests
        run: npm test

      - name: Run test coverage
        run: npm run test:coverage
        continue-on-error: true

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
        if: always()

  build-and-package:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build and package extension
        run: npm run package

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: bookdrive-extension-v*.zip
          retention-days: 30

  create-draft-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    needs: build-and-package
    if: startsWith(github.ref, 'refs/tags/') # Only run this job for new tags
    permissions:
      contents: write # Required to create a GitHub release
    steps:
      - name: Download packaged extension
        uses: actions/download-artifact@v4
        with:
          name: extension-package

      - name: Create Draft Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
          body: |
            ## New Release

            **Note:** This is a draft release. Please update the release notes with the relevant changes from your `CHANGELOG.md` or `RELEASE.md` before publishing.
            
            ### Changes
            - [ ] Add release notes here
            - [ ] Update version information
            - [ ] Review security updates
            
            ### Installation
            1. Download the extension package
            2. Extract the ZIP file
            3. Load the extension in your browser
          draft: true # This creates a draft release, it is NOT published automatically
          prerelease: false
          generate_release_notes: true
