name: BookDrive CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*' # Run on version tags like v1.0.0
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint:check

      - name: Run tests
        run: npm test

  build-and-package:
    runs-on: ubuntu-latest
    needs: lint-and-test # This job will only run if lint-and-test succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Package extension
        id: package
        run: |
          npm run package
          echo "zip_path=$(ls bookdrive-extension-v*.zip)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: ${{ steps.package.outputs.zip_path }}

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-package
    if: startsWith(github.ref, 'refs/tags/') # Only run this job for tags
    permissions:
      contents: write # Needed to create a release
    steps:
      - name: Download packaged extension
        uses: actions/download-artifact@v4
        with:
          name: extension-package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip" # Upload the zip file from the previous job
          body_path: "RELEASE.md" # Path to your release notes
          draft: false
          prerelease: false
